#%RAML 1.0 NamedExample

{
    "first_name": "Abebe",
    "last_name": "Bekele",
    "user_name": "abebe123",
    "password": "7815696ecbf1c96e6894b779456d330e",
    "birth_date": "1990-01-01",
    "phone": "0912345678",
    "email": "abebe@gmail.com",
    "address": "Addis Ababa",
    "role": "user"
}
