#%RAML 1.0 NamedExample

  {
    "first_name": "Abebe",
    "last_name": "Kebede",
    "user_name": "abebe.kebede",
    "password": "5f4dcc3b5aa765d61d8327deb882cf99",
    "birth_date": "1990-01-01",
    "phone": "+251912345678",
    "email": "abebe.kebede@example.com",
    "address": "Addis Ababa",
    "role": "user",
    "points": 0
  }